site_name: The Field Guide to Security Training in the Newsroom
pages:
    - Home: index.md
    - Chapter 1:
        - "Being a Better Trainer": Chapter01-01-BeingABetterTrainer.md 
        - "Training Games": Chapter01-02-TrainingGames.md
        - "Organizational Self-Assessment": Chapter01-03-OrganizationalSelfAssessment.md
        - "Setting the Stage for Your First Session": Chapter01-04-FramingStrategies.md
    - Chapter 2:
        - "Lesson: Mobile Security Settings": Chapter02-01-Mobile-Security-Settings.md 
        - "Lesson: Locking Down Mobile": Chapter02-02-Locking-Down-Mobile.md 
        - "Lesson: Setting Up Signal": Chapter02-03-Setting-Up-Signal.md 
        - "Lesson: Mobile Backups": Chapter02-04-Mobile-Backups.md 
        - "Lesson: Good Hygiene For Apps": Chapter02-05-Good-Hygiene-For-Apps.md
        - "Lesson: Passwords and Password Management": Chapter02-06-Passwords.md
        - "Lesson: Two-Factor Authentication": Chapter02-07-Two-Factor-Authentication.md
        - "Lesson: Phishing": Chapter02-08-Phishing.md
        - "Lesson: Physical Custody of Electronics": Chapter02-09-Physical-Security.md
        - "Lesson: Scrubbing Metadata": Chapter02-10-ScrubbingMetadata.md
        - "Lesson: Using SecureDrop Securely": Chapter02-11-SecureDrop.md
    - Chapter 3:
        - "Resources: Building Further Expertise": Chapter03-02-Resources.md
        - "Resources: Best Practices for a Tips Page": Chapter03-03-OrgBestPractices.md
    - Contribute to this guide: contributing.md
theme: readthedocs
